apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: simplejob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: simplejob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: cronjob:latest
            imagePullPolicy: IfNotPresent
            name: simplejob
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'
status: {}
